import { useMemo, useState } from 'react';
import './styles.css';

type ControlCategory = 'Combat' | 'Effects' | 'Visuals & Sounds' | 'Modes' | 'Multiplayer Safety';
type RiskLevel = 'Low' | 'Medium' | 'High';
type ControlType = 'slider' | 'toggle' | 'select';
type CreatorControl = { key:string; label:string; category:ControlCategory; type:ControlType; value:number|boolean|string; defaultValue:number|boolean|string; min?:number; max?:number; unit?:string; options?:string[]; risk:RiskLevel; source:'Detected'|'Suggested'; description:string; };

const categories: ControlCategory[] = ['Combat','Effects','Visuals & Sounds','Modes','Multiplayer Safety'];
const initialControls: CreatorControl[] = [
{ key:'sealedDamage', label:'Sealed Damage Bonus', category:'Combat', type:'slider', value:12, defaultValue:12, min:0, max:20, risk:'Medium', source:'Detected', description:'Controls how much extra damage this mode adds.'},
{ key:'shikaiDamage', label:'Shikai Damage Bonus', category:'Combat', type:'slider', value:6, defaultValue:6, min:0, max:20, risk:'High', source:'Detected', description:'Controls how much extra damage this mode adds.'},
{ key:'bankaiDamage', label:'Bankai Damage Bonus', category:'Combat', type:'slider', value:12, defaultValue:12, min:0, max:25, risk:'High', source:'Detected', description:'Controls how much extra damage this mode adds.'},
{ key:'transformCooldown', label:'Transformation Cooldown', category:'Combat', type:'slider', value:2, defaultValue:2, min:1, max:20, unit:'s', risk:'Medium', source:'Suggested', description:'Increase this if the ability feels too spammable.'},
{ key:'witherDuration', label:'Wither Duration', category:'Effects', type:'slider', value:5, defaultValue:5, min:0, max:12, unit:'s', risk:'High', source:'Detected', description:'Lower this if the effect feels too strong in PvP.'},
{ key:'blindnessDuration', label:'Blindness Duration', category:'Effects', type:'slider', value:4, defaultValue:4, min:0, max:12, unit:'s', risk:'High', source:'Detected', description:'Lower this if the effect feels too strong in PvP.'},
{ key:'weaknessLevel', label:'Weakness Level', category:'Effects', type:'select', value:'II', defaultValue:'II', options:['I','II','III'], risk:'Medium', source:'Suggested', description:'Lower this if the effect feels too strong in PvP.'},
{ key:'particles', label:'Particle Intensity', category:'Visuals & Sounds', type:'select', value:'High', defaultValue:'High', options:['Low','Medium','High'], risk:'Medium', source:'Detected', description:'Reduce this if particles feel too visually noisy.'},
{ key:'sounds', label:'Sound Effects Enabled', category:'Visuals & Sounds', type:'toggle', value:true, defaultValue:true, risk:'Low', source:'Suggested', description:'Turn this off for quieter sessions.'},
{ key:'sealedEnabled', label:'Sealed Mode Enabled', category:'Modes', type:'toggle', value:true, defaultValue:true, risk:'Low', source:'Suggested', description:'Enable or disable this mode quickly.'},
{ key:'shikaiEnabled', label:'Shikai Mode Enabled', category:'Modes', type:'toggle', value:true, defaultValue:true, risk:'Medium', source:'Suggested', description:'Enable or disable this mode quickly.'},
{ key:'bankaiEnabled', label:'Bankai Mode Enabled', category:'Modes', type:'toggle', value:true, defaultValue:true, risk:'High', source:'Suggested', description:'Enable or disable this mode quickly.'},
{ key:'pvpEnabled', label:'PvP Enabled', category:'Multiplayer Safety', type:'toggle', value:true, defaultValue:true, risk:'High', source:'Detected', description:'Controls if this mechanic applies in PvP.'},
{ key:'maxTargets', label:'Max Affected Targets', category:'Multiplayer Safety', type:'slider', value:6, defaultValue:6, min:1, max:12, risk:'High', source:'Suggested', description:'Lower this if crowd control feels too oppressive.'},
{ key:'disableSpawnLobby', label:'Disable in Spawn/Lobby', category:'Multiplayer Safety', type:'toggle', value:true, defaultValue:true, risk:'Medium', source:'Suggested', description:'Protects safe worlds from combat effects.'}
];

const PreviewToggle = ({ title, children }: { title: string; children: React.ReactNode }) => { const [open,setOpen]=useState(false); return <section className="panel"><button className="preview-head" onClick={()=>setOpen(!open)}><span>{title}</span><span>{open?'▾':'▸'}</span></button>{open&&<pre>{children}</pre>}</section>; };

export default function App(){
const [showControls,setShowControls]=useState(false); const [controls,setControls]=useState(initialControls);
const grouped = useMemo(()=>controls.reduce((a,c)=>{(a[c.category] ||= []).push(c); return a;}, {} as Record<ControlCategory,CreatorControl[]>),[controls]);
const changed = controls.filter(c=>c.value!==c.defaultValue);
const update=(key:string,val:number|boolean|string)=>setControls(prev=>prev.map(c=>c.key===key?{...c,value:val}:c));
const value=(c:CreatorControl)=>typeof c.value==='boolean'?(c.value?'On':'Off'):`${c.value}${c.unit??''}`;

return <div className="app"><main className="layout">
<nav className="top-nav"><div className="nav-left"><div className="logo">Creator Controls Demo</div>{['Explore','ModJams','Create','Structures','My Mods','My Servers'].map(i=><a key={i} className={`nav-item ${i==='Structures'?'active':''}`} href="#">{i}</a>)}</div><div className="nav-right"><button className="community-btn">Join our community</button><button className="pro-badge">PRO Unlimited Mods</button><button className="avatar" /></div></nav>
<section className="mod-header"><div><a className="back-link" href="#"><span>◀</span><span>Back</span></a><div className="pill-row"><span className="pill">v1</span><span className="pill">MC Java 1.21.5</span></div><h1>Soul Reaper Kyoraku Blade</h1><div className="meta-row"><span>↓ 1 download</span><span className="tag">Combat</span><span className="tag">Tool</span><span className="tag">+ Add more</span><span>◌ Unlisted</span></div></div><div className="header-actions"><button className="icon-btn">⋮</button><button className="icon-btn">⇩</button><button className="action-btn">Share</button><button className="action-btn">Publish</button><button className="play-btn">▶ Play</button></div></section>
<section className="preview-area"><div className="sword-card"><div className="pixel-sword" /></div><div className="recipe-preview-card"><div className="recipe-grid compact">{[...Array(9)].map((_,i)=><div key={i} className="cell" />)}</div><span>➜</span><div className="result-cell" /></div></section>
<div className="tabs"><button className="tab">Description</button><button className="tab active">Versions & Editing</button><button className="tab">Comments</button></div>
<div className="content-grid"><div><section className="panel edit-panel"><h2>Edit this Mod</h2><p>This will create a new mod based on "Soul Reaper Kyoraku Blade" with your modifications.</p><textarea rows={6} placeholder="Describe the changes you want to make..." /><div className="edit-footer"><span className="advanced">NEW Advanced options (optional)</span><button className="play-btn">Create New Version</button></div><div className="creator-row"><div><h3>Creator Controls</h3><p>Tweak damage, cooldowns, effects, and visuals without rewriting your prompt.</p><small>Prompt edits are great for creative changes. Creator Controls are for small tuning changes: make an ability weaker, reduce particles, increase cooldowns, or disable a mode without regenerating the whole idea.</small></div><button className="action-btn" onClick={()=>setShowControls(true)}>Add Creator Controls</button></div></section>
{showControls&&<section className="panel"><div className="cc-head"><h2>Creator Controls</h2><div><span className="pill">Fabric 1.21.5</span><span className="pill">Prototype</span></div></div><p className="muted">Detected tunable values from this generated mod. Adjust them visually, then export a tuned version.</p>{categories.map(cat=><div className="category" key={cat}><h3>{cat}</h3>{(grouped[cat]||[]).map(c=><div className="control-row" key={c.key}><div className="row-top"><strong>{c.label}: {value(c)}</strong><span className={`risk ${c.risk.toLowerCase()}`}>{c.risk}</span></div>{c.type==='slider'&&<input className="slider" type="range" min={c.min} max={c.max} value={Number(c.value)} onChange={e=>update(c.key,Number(e.target.value))} />}{c.type==='toggle'&&<button className="toggle-btn" onClick={()=>update(c.key,!Boolean(c.value))}>{Boolean(c.value)?'On':'Off'}</button>}{c.type==='select'&&<select value={String(c.value)} onChange={e=>update(c.key,e.target.value)}>{c.options?.map(o=><option key={o}>{o}</option>)}</select>}<div className="row-meta"><span>{c.description}</span><span className="source">{c.source}</span></div></div>)}</div>)}{changed.length>0&&<div className="changes"><h3>What changed</h3>{changed.map(c=><div key={c.key}>• {c.label} changed from {String(c.defaultValue)}{c.unit??''} → {String(c.value)}{c.unit??''}</div>)}</div>}<div className="export-row"><button className="play-btn">Export Tuned Version</button><small>This prototype shows the UI and refactor concept. In production, CreativeMode’s build pipeline would generate the tuned JAR.</small></div><PreviewToggle title="Advanced Preview: Fabric tuning schema">{JSON.stringify({type:'weapon',controls:controls.map(({key,value})=>({key,value}))},null,2)}</PreviewToggle><PreviewToggle title="Advanced Preview: Before / after implementation">{`Before:\ntarget.addStatusEffect(new StatusEffectInstance(StatusEffects.BLINDNESS, 80, 0));\n\nAfter:\ntarget.addStatusEffect(new StatusEffectInstance(\n  StatusEffects.BLINDNESS,\n  CreatorControls.effects.bankaiBlindnessDurationTicks,\n  CreatorControls.effects.bankaiBlindnessAmplifier\n));`}</PreviewToggle><PreviewToggle title="Advanced Preview: Rebuild notes">{`Advanced preview for implementation only. Users would interact with the controls above.`}</PreviewToggle></section>}
<section className="version-history"><h2>Version History</h2><div className="history-tabs"><button className="tab active">Active</button><button className="tab">Discarded</button></div><div className="panel version-card"><div className="version-top"><div><strong>v1</strong> <span className="status">Current</span> <span className="status complete">Complete</span></div><span>Apr 29, 2026, 12:22 AM  ↓ 1</span></div><p><strong>User request:</strong> Create a new Minecraft weapon. Appearance: Create a soul reaper sword of Shunsui Kyoraku. Behavior: It should have a whole shikai and bankai.</p><div className="feature-row"><strong>› Feature Implementation</strong><span>100% success rate</span></div></div></section></div>
<aside className="sidebar"><section className="panel sidebar-card"><div className="recipe-grid">{[...Array(9)].map((_,i)=><div key={i} className="cell" />)}</div><h3>Recipe</h3><p>Visually edit crafting recipes for your custom items.</p><button className="purple-btn">Open Recipe Editor</button></section><section className="panel sidebar-card"><h3>Port this Mod</h3><p>This will create a new version for Minecraft Java 1.20.1.</p><button className="outline-btn">Port to Java 1.20.1</button></section></aside></div>
</main></div>
}
